config/routes.rb
Rails.application.routes.draw do
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  get 'pages/main'

  get 'pages/blog'

  get 'pages/porfolio'

  root to: 'pages#main'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,       :validate => true
  attribute :email,      :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phonenumber, :validate => /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/
  attribute :message
  

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "NicolasDev Contact",
      :to => "nbr625@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.valid?
      ContactMe.contact_email(@contact).deliver
      redirect_to root_path
      flash[:notice] = "Thank you, {@contact.name}. I will return your message promptly."
    else     
      render :new
      flash.now[:error] = 'Could not send message as is. Please recheck email and phone fields.'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end

  def blog
  end

  def porfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact_me/contact_email.html.erb
<h1>New Contact!</h1>
<p>Message from: <%= @contact.name%></p>
<p>Email: <%= @contact.email %></p>
<p>Phone Number: <%= @contact.phonenumber %></p>
<p>
  <%=@contact.message %>
</p>

app/views/contact_me/contact_email.text.erb
Message from: <%= @contact.name%>
Email: <%= @contact.email %>
Phone Number: <%= @contact.phonenumber %>

<%=@contact.message %>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<div align="center" style="width: 80%; margin-left: 10%;">
  <h1 class="header">Contact Nicolas</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <div style="width: 70%; margin-left: 15%; margin-right: 15%;">
    	<div style="text-align: center;"><%= f.input :name, :required => true, style: "width: 70%; margin-left: 15%; margin-right: 15%;" %></div>
    </div>
    <div style="width: 70%; margin-left: 15%; margin-right: 15%;"><%= f.input :email, :required => true %></div>
    <div style="width: 70%; margin-left: 15%; margin-right: 15%;"><%= f.input :phonenumber, :required => false %>(Optional)</div>
    <%= f.input :message, :as => :text, :required => true %>
    <div>
      </br>
      <footer class="page-footer teal">
        <div class="container">
          <div class="row">
            
            <div style="text-align: center;">
              <ul>
                <li><div><%= f.button :submit, 'Blast off!', :class=> "btn btn-primary" %></div></li>
                
              </ul>
            </div>
          </div>
        </div>

  
      </footer>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NicolasDev</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  

  <link href='https://fonts.googleapis.com/css?family=Courgette' rel='stylesheet' type='text/css'>
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <script src="jquery-2.0.2.min.js"></script>
</head>
<body>





<%= yield %>





<script type="text/javascript">
  $( window ).load(function() { 
    $('.parallax').parallax();
  });

</script>
<script type="text/javascript">
  $( window ).load(function() { 
    $(function() {
        $.preloadCssImages();
    });
  };
   
</script>

<script type="text/javascript">

    // Simple elevator usage.
  var elementButton = document.querySelector('.elevator');
  var elevator = new Elevator({
    element: elementButton,
    mainAudio: './audio/elevator.mp3', // Music from http://www.bensound.com/
    endAudio: './audio/ding.mp3',
    duration: 3000
  });

</script>
<script type="text/javascript">
  $( window ).load(function() { 
    jQuery.preloadCssImages = function(){

      var allImgs = [];//new array for all the image urls  
      var k = 0; //iterator for adding images
      var sheets = document.styleSheets;//array of stylesheets

      for(var i = 0; i0 && imgUrls != ''){//loop array

          var arr = jQuery.makeArray(imgUrls);//create array from regex obj        

          jQuery(arr).each(function(){
            allImgs[k] = new Image(); //new img obj
            allImgs[k].src = (this[0] == '/' || this.match('http://')) ? this : baseURL + this;     //set src either absolute or rel to css dir
            k++;
          });
        }
      }//loop
      return allImgs;
    }

    $.preloadCssImages();



    var preloadedImgs = $.preloadCssImages();


  });
</script>
</body>

</html>

app/views/pages/blog.html.erb
<h1>This is the blog</h1>



<div class="space-frame"
2
     data-enter="rotateInQuarterClockwise fadeIn"
3
     data-exit="fadeOut scaleOut"
4
     data-duration="1.3">
5
  <section class="space-inner-frame">
6
    <p>Content goes here</p>
7
  </section>
8
</div>
<div class="space-frame"
2
     data-enter="rotateInQuarterClockwise fadeIn"
3
     data-exit="fadeOut scaleOut"
4
     data-duration="1.3">
5
  <section class="space-inner-frame">
6
    <p>balablabalbalbalbalbalbalbalbalablablablabalbalbalabalbalbalablabalbalbalbalbal</p>
7
  </section>
8
</div>
<div class="space-frame"
2
     data-enter="rotateInQuarterClockwise fadeIn"
3
     data-exit="fadeOut scaleOut"
4
     data-duration="1.3">
5
  <section class="space-inner-frame">
6
    <p>Content goes here</p>
7
  </section>
8
</div>

<script src="space.js"></script>

app/views/pages/main.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">

      <h1 class="header center teal-text text-lighten-2">Nicolas Dev</h1>
      <div class="row center">
        <h5 class="header col s12 light">Experience Development</h5>
      </div>
      <div class="row center">
        
      </div>


    </div>
  </div>
  <div class="parallax"><%=image_tag('bg1.jpg', alt: "Oops how embarrassing please reload the page")%></div>

</div>


<div class="container" style="margin-top: 0px;">
  <div class="section">
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><%= link_to  image_tag('portfolio.png', height: '82', width: '82'), pages_porfolio_path %></h2>
          <h5 class="center">Porfolio</h5>
          <p class="light"></p>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><%= link_to image_tag('github.png', height: '82', width: '82'), "https://github.com/nbr625", :target => "_blank"%></h2>
          <h5 class="center">Github</h5>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><%= link_to image_tag('contact.png', height: '82', width: '82'), new_contact_path %></h2>
          <h5 class="center">Message Me</h5>
          <p class="light"></p>
        </div>
      </div>
    </div>
  </div>
</div>





<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 center">
        <h3><%= image_tag('nicolasthumb.png', height: '300', width: '310')%></h3>
        <h5>About Me</h5>
        <p style="font-size: 20px;">My name is Nicolas Berrizbeitia, I am a human male and I love to create. My job is to build responsive, professional platforms that suit the needs of my clients
        these are the technologies I use for this goal:</p>
        <br/>

        <ul>
          <li>
            <h5 class="center">Programming Languages</h5>
            <p class="light" style="font-size: 18px; color: #8772EC">Ruby, JavaScript, Angular.js</p>
          </li>
          <br/>
          <li>
            <h5 class="center">Databases and Servers</h5>
            <p class="light" style="font-size: 18px; color: #8772EC">MySql, Postgres, Amazon S3</p>
          </li>
          <br/>
          <li>
            <h5 class="center">Frameworks</h5>
            <p class="light" style="font-size: 18px; color: #8772EC">Rails, RSpec, FactoryGirl, Capybara, Selenium</p>
          </li>
          <br/>
          <li>
            <h5 class="center">Views</h5>
            <p class="light" style="font-size: 18px; color: #8772EC">HTML, HAML, XML, CSS, JSON, ERB, JQuery, Ajax.</p>
          </li>
        </ul>

        <br/><br/>

        <p style="font-size: 20px;">Thats my job. My passion is:</p>
      </div>
    </div>
  </div>
</div>



<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light" id="paratwo">... Is crafting immersive web experiences.</h5>
      </div>
    </div>
  </div>


  <div class="parallax"><%=image_tag('bg2.jpg')%></div>
</div>







<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>How?</h4>
        <p style="font-size: 20px;">by focusing on:</p>
        <br/>
        <br/>
        <p style="font-size: 20px;">Balanced, <span class="purple_accent">stimulating</span> designs</p><br/><br/>
        <p style="font-size: 20px;">The <span class="purple_accent">psychology</span> of Target Audience</p><br/><br/>
        <p style="font-size: 20px;">Solid Code base that safeguards <span class="purple_accent">immersion</span></p>
        <p style="font-size: 20px;">And most importantly...</p><br/><br/>
        <ul id="staggered-test">
          <li class="purple_accent s40">The element of Surpirse</li>
        </ul>
      </div>
    </div>
  </div>
</div>




<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light" style="float: right; font-family: 'Courgette', cursive; font-size: 40px; margin-bottom: 65%;" id="parathree">A website is not a page...</h5>
      </div>
    </div>
  </div>
  <div class="parallax" ><%=image_tag('book.png')%></div>
</div>



<div class="parallax-container valign-wrapper" style="height: 900px;">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light" id="parafour" style="font-size: 50px; margin-top: -50%; font-family: 'Courgette', cursive; color: black;">It is an experience in the mind of the beholder.</h5>
      </div>
    </div>
  </div>
  <div class="parallax" src="https://dumpyourphoto.com/photo/mAcplc3mPL" alt="Unsplashed background img 1"><%= image_tag("brainbanner1.gif", alt: "Unsplashed background img 1")%></div>
</div>
<br/>
<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 center">
        <p style="font-size: 40px;">Webdevelopment is a techonological marvel bordering on magic. <span class="purple_accent">Let's remind them of that.</span></p>
      </div>
    </div>
  </div>
</div>
<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      
      <div style="text-align: center;">
        <h5 class="white-text">Going up <span class="pf_cite">?</span></h5>
        <ul>
          <li><div class="elevator waves-effect waves-light btn">Yes!</div></li>
          
        </ul>
      </div>
    </div>
  </div>

  
</footer>
  <!--  Scripts-->

<script type="text/javascript" src="space.js"></script>
<script type="text/javascript">
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>
<script type="text/javascript">
  var options = [
    {selector: '#staggered-test', offset: 200, callback: 'Materialize.showStaggeredList("#staggered-test", 3000)' }
  ];
  Materialize.scrollFire(options);
    
</script>
<script type="text/javascript">
  $(document).ready(function(){
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
  });
</script>

app/views/pages/porfolio.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">

      <h1 id="pf" class="header col s12 light" style="color: white;">Nicolas Dev</h1>
      <div class="row">
        <h5 id="pf" class="header col s12 light">Experience Development</h5><br/><br/>
        <br/>
        <%= link_to 'Home', root_path, class: "btn btn-primary" %>
      </div>
      <div class="row center">
        
      </div>


    </div>
  </div>
  <div class="parallax" src="https://dumpyourphoto.com/photo/mAcplc3mPL" alt="Unsplashed background img 1"><%= image_tag("brainbanner1.gif", alt: "Unsplashed background img 1")%></div>
</div>


<div class="panel panel-default">
	<div class="panel-body">
		<h1 class="pf_title">Portfolio</h1><br/>

		<p class="pf_quote">"Just keep going like crazy and look back when it's over. Otherwise you just get confused."<span class="pf_cite">-Cliff Burton</span><p>

		<br/><br/>



		<div class="container" id="portfolio" style="width:80%; text-align: center;">
			<ul id="staggered-test">
				<li class="porfolio_pic_container tooltip tooltip-turnright" id="artware8" tooltip-content="Comment 1"><img><%= image_tag('artware1.jpg', class: "masonryImage tooltip-item right-content")%></img><span class="tooltip-content">Artware is an international plaform for designers. Together, the member of the site shape the brand Artware, according to their collective aethetic sense. The community provides opportunities for talented people from turbulent political/economic climates.</span>
				</li>

				<li class="porfolio_pic_container tooltip tooltip-turnleft" id="artware7" tooltip-content="Comment 2"><img><%= image_tag('artware7.jpg', class: "masonryImage tooltip-item right-content")%></img><span class="tooltip-content left_content">The ratings determine the brand. The higher the rating, the more likely this design is to be printed.</span>
				</li>

				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="artware1" style="float: left;" tooltip-content="Comment 3"><%= image_tag('artware2.jpg', class: "masonryImage")%><span class="tooltip-content left_content">The design of site itself denotes a vibrant, wantom expressiveness. This energy is balanced by the of relaxing black that proliferates most of the empty space. The illusion of an underground society creates a natural habitat for artistic temperaments.</span>
					
				</li>

				<li class="porfolio_pic_container tooltip-turnright tooltip" id="artware2" style="float: left;"><img><%= image_tag('artware3.jpg', class: "masonryImage right-content")%></img><span class="tooltip-content">Shopping is easy; simply select the quanity and add it to the cart. The amount is changed immediately and not on page load. Only prints approved by the community make it this far; costumers can rest easy knowing that they are buying something that has been refined. They are making the world more artful with your purchase!</span>
					
				</li>
				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="artware3" style="float: left;"><img><%= image_tag('artware4.jpg', class: "masonryImage")%></img><span class="tooltip-content left_content">This page allows admins to see what prints have the best rating and most pleges. They can also see what products are out of stock and what designs have been flagged by other users. Products can also be added from this page. Any user that is not an admin is redirected to the homepage</span>
				</li>
				<li class="porfolio_pic_container tooltip-turnright tooltip" id="artware4" style="float: left;"><img><%= image_tag('artware5.jpg', class: "masonryImage")%></img><span class="tooltip-content right-content">Here we have one of the potential prints. In addition to rating and critiquing, users can "pledge" for the design. This is a promise that they will buy the design if it is printed. They are awarded with a 50% discount on purchase! The colored fist icon tells how many pledges have been submitted for this print. Admins can turn this design into a product directly from this page with just a button and confirmation.</span>
					
				</li>

				<li class="porfolio_pic_container tooltip-turnright tooltip" id="artware5" style="float: left;"><img><%= image_tag('artware6.jpg', class: "masonryImage")%></img><span class="tooltip-content right-content">The review page displays all recent prints in a leafed structure. Additionally, the side contains articles about art theory and current trends. This reiforces the idea of a hangout, instead a pure store.</span>
					
				</li>
			</ul>

		</div>

		<div style="text-align: center;"><%= link_to 'Visit Artware', 'https://artwear.herokuapp.com/', class: "btn btn-primary" %></div>
		<br/>

		<div class="container" id="portfolio" style="width; 80%; text-align: center;">
			<ul id="staggered-test2">
		  

				<li class="porfolio_pic_container tooltip-turnright tooltip" style="float: left; width: 100%"><img><%= image_tag('ml1.jpg', class: "masonryImage")%></img><span class="tooltip-content right-content">Movielauch in a video streaming site that funnels science fiction afficionados in one place. Everything in the site maintains the ambiance of endless space, endless possibility. To infinity and a bit further...</span></li>
			
				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="ml1" style="float: left;"><img><%= image_tag('ml2.jpg', class: "masonryImage")%></img><span class="tooltip-content left_content">From the onset, the visitors are introduced to the offbeat, communial tone of the site.</span></li>
				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="ml5.jpg" style="float: left;"><img><%= image_tag('ml4', class: "masonryImage")%><img><span class="tooltip-content left_content">This is a regular review page, each user provides a certain amount of "starpower" to the movie. The movie get a star category according to their average rating</span></li>
				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="star"><span class="tooltip-content"></span><img><%= image_tag('empty_space.jpg', class: "masonryImage")%></img><span class="tooltip-content right-content">A movie without a review gets this. It set the anticipation of something more.</span></li>
				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="star"><img><%= image_tag('orange_dipper.jpg', class: "masonryImage")%></img><span class="tooltip-content right-content">the orange dimmer, only slightly hotter than our sun. 2/5</span></li>

				
				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="star" style="margin-bottom: 1%;"><img><%= image_tag('blue_giant.jpg', class: "masonryImage")%></img><span class="tooltip-content">Blue Giant the hottest stars in the obsidian vacuum. The heat generated in unimaginable 5/5</span></li>

				<li class="porfolio_pic_container tooltip-turnright tooltip" id="star"><img><%= image_tag('white_giant.jpg', class: "masonryImage")%></img><span class="tooltip-content right-content">White Giants, pearls in the rough. Only second in heat to the Blue Giants 4/5</span></li>

				<li class="porfolio_pic_container tooltip-turnright tooltip" id="ml4" style="float: left;"><img><%= image_tag('ml3.jpg', class: "masonryImage")%><span class="tooltip-content right-content">This movie is in dire need of a review. It is currently suspended in empty space.</span></img></li>
				<li class="porfolio_pic_container tooltip-turnleft tooltip" id="ml2" style="float: left;"><img><%= image_tag('ml5.jpg', class: "masonryImage")%><span class="tooltip-content left_content">This is what an user profile looks like.  last reviewed movie and also awards a star rating to the user according to the activity level. This conforms the idea of establishing progression to get users invested. Blue Giant reviews are more well regarded than Orange Dwarfs...</span></img></li>

				<li class="porfolio_pic_container tooltip-turnright tooltip" id="ml6.jpg" style="float: left;"><img><%= image_tag('ml6', class: "masonryImage") %><span class="tooltip-content right-content">Withing the e category of science fiction there are many subcategories, including Action, Animation, Romance, etc. We provide a large variety that allows users to find exactly what they are itching for at the momment.</span></img></li>
			</ul>

			
		</div>

		<div style="text-align: center;"><%= link_to 'Visit Movielauch', 'https://movielaunch.herokuapp.com/', class: "btn btn-primary" %></div>
	</div>
</div>

<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      
      <div style="text-align: center;">
        <h5 class="white-text">Going up <span class="pf_cite">?</span></h5>
        <ul>
          <li><div class="elevator waves-effect waves-light btn">Yes!</div></li>
          
        </ul>
      </div>
    </div>
  </div>

  
</footer>
<script>
    $(window).scrollTop(0);
</script>

<script type="text/javascript">
  var options = [
    {selector: '#staggered-test', offset: 100, callback: 'Materialize.showStaggeredList("#staggered-test", 3000)' }, 
    {selector: '#staggered-test2', offset: 100, callback: 'Materialize.showStaggeredList("#staggered-test2", 3000)' }
  ];
  Materialize.scrollFire(options);
    
</script>